sudo: required
dist: xenial
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    recipients:
      - isaac.saito@plusonerobotics.com

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - AFTER_SCRIPT="echo 'Run custom test'; python src/realsense/realsense2_camera/scripts/rs2_test.py --all"
    - BEFORE_SCRIPT="./.install_dependency.sh; echo 'download data' && bag_filename='http://realsense-hw-public.s3.amazonaws.com/rs-tests/TestData/outdoors.bag' && wget $bag_filename -P 'records/'"

  matrix:
    - ROS_DISTRO="kinetic"   ROS_REPO=ros
    - ROS_DISTRO="kinetic"   PRERELEASE=true
    - ROS_DISTRO="melodic"   ROS_REPO=ros
    - ROS_DISTRO="melodic"   PRERELEASE=true
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
